"""review system 2.0

Revision ID: 32e62b22cee0
Revises: 10b399f23d11
Create Date: 2021-04-21 15:49:17.515832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e62b22cee0'
down_revision = '10b399f23d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('table', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
