"""review system 4.0

Revision ID: 61c313e32dcf
Revises: cb541c3c89e9
Create Date: 2021-04-21 15:57:53.126113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c313e32dcf'
down_revision = 'cb541c3c89e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('table',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('table',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
