"""review system 4.0

Revision ID: cb541c3c89e9
Revises: e0cbbb2266b9
Create Date: 2021-04-21 15:55:57.898826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb541c3c89e9'
down_revision = 'e0cbbb2266b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'table',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'table',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
