"""review system 2.0

Revision ID: e0cbbb2266b9
Revises: 32e62b22cee0
Create Date: 2021-04-21 15:51:46.458175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cbbb2266b9'
down_revision = '32e62b22cee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('table', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
